name: build

permissions:
  contents: write

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: >-
            zip
            unzip
            curl
      - uses: actions/checkout@v4
      - name: download
        shell: msys2 {0}
        id: build
        run: |
          # powershell ./build.ps1
          bash ./build.sh

      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.build.outputs.tag }}
          artifacts: "dist/*.zip"
          allowUpdates: true