name: build

permissions:
  contents: write

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: download
        run: |
          # powershell ./build.ps1
          bash ./build.sh

      - name: release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "dist/*.zip"
          allowUpdates: true